"""adjust question and concept tables

Revision ID: 35908e8addc7
Revises: aa915ac730e5
Create Date: 2026-07-23 14:41:19.251040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35908e8addc7'
down_revision: Union[str, Sequence[str], None] = 'aa915ac730e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concept', schema=None) as batch_op:
        batch_op.drop_column('difficulty')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attacker_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('defender_id', sa.Integer(), nullable=False))
        batch_op.alter_column('answer',
               existing_type=sa.VARCHAR(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.create_foreign_key(batch_op.f('fk_question_attacker_id_pokemon_type'), 'pokemon_type', ['attacker_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_question_defender_id_pokemon_type'), 'pokemon_type', ['defender_id'], ['id'])
        batch_op.drop_column('text')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_question_defender_id_pokemon_type'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_question_attacker_id_pokemon_type'), type_='foreignkey')
        batch_op.alter_column('answer',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
        batch_op.drop_column('defender_id')
        batch_op.drop_column('attacker_id')

    with op.batch_alter_table('concept', schema=None) as batch_op:
        batch_op.add_column(sa.Column('difficulty', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
