"""initial schema

Revision ID: 903cf118e7f1
Revises: 
Create Date: 2026-06-29 13:54:31.609990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '903cf118e7f1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concept',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pokemon_species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('pokemon_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('meta_usage_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pokemon_id', sa.Integer(), nullable=False),
    sa.Column('usage_percentage', sa.Float(), nullable=False),
    sa.Column('from_month', sa.Date(), nullable=False),
    sa.Column('format_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon_species.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pokemon_to_type_association',
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('pokemon_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pokemon_type_id'], ['pokemon_type.id'], ),
    sa.ForeignKeyConstraint(['species_id'], ['pokemon_species.id'], ),
    sa.PrimaryKeyConstraint('species_id', 'pokemon_type_id')
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concept.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('type_matchup',
    sa.Column('attacker', sa.Integer(), nullable=False),
    sa.Column('defender', sa.Integer(), nullable=False),
    sa.Column('multiplier', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['attacker'], ['pokemon_type.id'], ),
    sa.ForeignKeyConstraint(['defender'], ['pokemon_type.id'], ),
    sa.PrimaryKeyConstraint('attacker', 'defender')
    )
    op.create_table('answer_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer_record')
    op.drop_table('type_matchup')
    op.drop_table('question')
    op.drop_table('pokemon_to_type_association')
    op.drop_table('meta_usage_data')
    op.drop_table('user_data')
    op.drop_table('pokemon_type')
    op.drop_table('pokemon_species')
    op.drop_table('concept')
    # ### end Alembic commands ###
