"""initial_schema

Revision ID: aa915ac730e5
Revises: 
Create Date: 2026-07-06 10:45:26.379888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa915ac730e5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concept',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_concept'))
    )
    op.create_table('pokemon_species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pokemon_species')),
    sa.UniqueConstraint('name', name=op.f('uq_pokemon_species_name'))
    )
    op.create_table('pokemon_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pokemon_type')),
    sa.UniqueConstraint('name', name=op.f('uq_pokemon_type_name'))
    )
    op.create_table('user_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_data')),
    sa.UniqueConstraint('email', name=op.f('uq_user_data_email')),
    sa.UniqueConstraint('username', name=op.f('uq_user_data_username'))
    )
    op.create_table('meta_usage_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pokemon_id', sa.Integer(), nullable=False),
    sa.Column('usage_percentage', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon_species.id'], name=op.f('fk_meta_usage_data_pokemon_id_pokemon_species')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meta_usage_data')),
    sa.UniqueConstraint('pokemon_id', name=op.f('uq_meta_usage_data_pokemon_id'))
    )
    op.create_table('pokemon_to_type_association',
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('pokemon_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pokemon_type_id'], ['pokemon_type.id'], name=op.f('fk_pokemon_to_type_association_pokemon_type_id_pokemon_type')),
    sa.ForeignKeyConstraint(['species_id'], ['pokemon_species.id'], name=op.f('fk_pokemon_to_type_association_species_id_pokemon_species')),
    sa.PrimaryKeyConstraint('species_id', 'pokemon_type_id', name=op.f('pk_pokemon_to_type_association'))
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concept.id'], name=op.f('fk_question_concept_id_concept')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question'))
    )
    op.create_table('type_matchup',
    sa.Column('attacker', sa.Integer(), nullable=False),
    sa.Column('defender', sa.Integer(), nullable=False),
    sa.Column('multiplier', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['attacker'], ['pokemon_type.id'], name=op.f('fk_type_matchup_attacker_pokemon_type')),
    sa.ForeignKeyConstraint(['defender'], ['pokemon_type.id'], name=op.f('fk_type_matchup_defender_pokemon_type')),
    sa.PrimaryKeyConstraint('attacker', 'defender', name=op.f('pk_type_matchup'))
    )
    op.create_table('answer_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], name=op.f('fk_answer_record_question_id_question')),
    sa.ForeignKeyConstraint(['user_id'], ['user_data.id'], name=op.f('fk_answer_record_user_id_user_data')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_answer_record'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer_record')
    op.drop_table('type_matchup')
    op.drop_table('question')
    op.drop_table('pokemon_to_type_association')
    op.drop_table('meta_usage_data')
    op.drop_table('user_data')
    op.drop_table('pokemon_type')
    op.drop_table('pokemon_species')
    op.drop_table('concept')
    # ### end Alembic commands ###
